# Generated by Django 5.2.3 on 2025-06-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_is_compelted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_compelted',
            new_name='is_completed',
        ),
    ]
